#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96			# Set DPI. User may want to use a larger number for larger screens.
battlestation &			# Configure monitor resolution.
nitrogen --restore &	# Set background using nitrogen.
xset s off -dpms &		# Disable Sleep. WARNING If you are using an oled, disable this.
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="xcompmgr dunst unclutter pipewire remapd blueman-applet"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
